= OS Migrate Documentation
:toc: left
:toclevels: 2
:sectnums:
:sectlinks:
:icons: font

// Introduction & Bug Reporting
== Welcome to OS Migrate

OS Migrate provides a framework and toolsuite for exporting and importing
resources between two clouds. It's a collection of Ansible playbooks that
provide the basic functionality, but may not fit each use case out of
the box. You can craft custom playbooks using the OS Migrate
collection pieces (roles and modules) as building blocks.

At present OS Migrate supports migration from VMware clouds to OpenStack,
and OpenStack to OpenStack.

OS Migrate strictly uses the official OpenStack API and does not
utilize direct database access or other methods to export or import
data. The Ansible playbooks contained in OS Migrate are idempotent.
If a command fails, you can retry with the same command.

== Community

The https://github.com/os-migrate/os-migrate[source code of OS Migrate]
is hosted on GitHub.

For issue reports please use the GitHub
https://github.com/os-migrate/os-migrate/issues[OS Migrate issue tracker].

To get help, feel free to also create an
https://github.com/os-migrate/os-migrate/issues[issue]
on GitHub with your question.

If you want to contribute to the project (code, docs, ...), please
refer to the link:developer/index.adoc[developer docs].

== Contents

// Quickstart
include::operator/index.adoc[leveloffset=+1]

// Developer
include::developer/index.adoc[leveloffset=+1]

// Reference
include::reference/modules/index.adoc[leveloffset=+1]

include::reference/roles/index.adoc[leveloffset=+1]


