= OS Migrate Documentation
:toc: left
:toclevels: 2
:sectnums:
:sectlinks:
:icons: font

// Introduction & Bug Reporting
== Welcome to OS Migrate

OS Migrate provides a framework and toolsuite for exporting and importing
resources between two clouds. It's a collection of Ansible playbooks that
provide the basic functionality, but may not fit each use case out of
the box. You can craft custom playbooks using the OS Migrate
collection pieces (roles and modules) as building blocks.

At present OS Migrate supports migration from VMware clouds to OpenStack,
and OpenStack to OpenStack.

OS Migrate strictly uses the official OpenStack API and does not
utilize direct database access or other methods to export or import
data. The Ansible playbooks contained in OS Migrate are idempotent.
If a command fails, you can retry with the same command.

include::source/operator-vmware-guide.adoc[leveloffset=+1]

include::source/operator-aee.adoc[leveloffset=+1]

include::source/operator-performance-expectations.adoc[leveloffset=+1]

== Community

https://github.com/os-migrate/vmware-migration-kit/[GitHub hosted source code]

For issue reports please use the GitHub
https://github.com/os-migrate/vmware-migration-kit/issues[issue tracker]
