= OS Migrate Documentation
:toc: left
:toclevels: 3
:sectnums:
:sectlinks:
:sectanchors:
:source-highlighter: rouge
:imagesdir: images

== Welcome to OS Migrate

OS Migrate provides a framework and tool suite for exporting and importing resources between clouds. It is a collection
of Ansible playbooks that provide the base functionality, and you can craft custom playbooks from the OS Migrate roles
and modules as building blocks.

OS Migrate supports two migration paths:

* Migrating virtual machines from VMware to OpenStack, using the `os_migrate.vmware_migration_kit` collection.
* Migrating workloads and resources between OpenStack clouds, using the `os_migrate.os_migrate` collection.

OS Migrate uses the official OpenStack API and does not use direct database access or other methods to export or import
data. The Ansible playbooks are idempotent: if a command fails, you can retry it with the same command.

This documentation is organized into two guides that share a common reference:

* xref:vmware-to-openstack[Migrating virtual machines from VMware to OpenStack]
* xref:openstack-to-openstack[Migrating workloads between OpenStack clouds]
* xref:common-reference[Common reference]

include::source/vmware/assembly_vmware-migration.adoc[leveloffset=+1]

include::source/os-to-os/assembly_os-to-os-migration.adoc[leveloffset=+1]

include::source/shared/assembly_common-reference.adoc[leveloffset=+1]

== Community

https://github.com/os-migrate/vmware-migration-kit/[VMware Migration Kit source code]

https://github.com/os-migrate/os-migrate/[OS Migrate source code]

For issue reports, use the GitHub issue trackers of the
https://github.com/os-migrate/vmware-migration-kit/issues[VMware Migration Kit] and
https://github.com/os-migrate/os-migrate/issues[OS Migrate] repositories.
